### ISSUE TITLE
Getting this error after installing all modules, should I just remove all console color shi?

### ISSUE THREAD

**Issue by brimmlessyankee** [H4cK3dR4Du/Spotify-Account-Generator#2]
Traceback (most recent call last):
  File "C:\Users\djurb\Desktop\Programming\Spotify-Account-Generator-main\main.py", line 33, in <module>
    red = fg(1)
  File "C:\Python310\lib\site-packages\colored\colored.py", line 276, in fg
    return Colored(name).foreground()
  File "C:\Python310\lib\site-packages\colored\colored.py", line 48, in __init__
    self.enable_windows_terminal_mode()
  File "C:\Python310\lib\site-packages\colored\colored.py", line 145, in enable_windows_terminal_mode
    ok = windll.kernel32.SetsConsoleMode(wintypes.HANDLE(hStdout), mode)
  File "C:\Python310\lib\ctypes\__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python310\lib\ctypes\__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'SetsConsoleMode' not found. Did you mean: 'GetConsoleMode'?

**Comment by H4cK3dR4Du** [comment]
Yeah Bro, this is common error. To fix that i give you an example:

red = fg(1)
purple = fg(5)
reset = fg(7)

----------------

red = ""
purple = ""
reset = ""

Replace all color variables (fg) with ""
